version: '3'

services:
  db:
    image: postgres:alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  web:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - GOOGLE_API_KEY=${FEATS_FOOLS_GOOGLE_API_KEY}

volumes:
  postgres-data:
