# Generated by Django 2.0.3 on 2018-03-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceevent',
            name='description',
            field=models.TextField(help_text='User-facing description of this event. max: 150 characters', max_length=150),
        ),
        migrations.AlterField(
            model_name='danceevent',
            name='location',
            field=models.CharField(help_text='Approximate location of this event, e.g. Newton, MA. max: 60 characters', max_length=60),
        ),
        migrations.AlterField(
            model_name='danceevent',
            name='occurrence',
            field=models.DateField(help_text='Example date of this event, used with frequency to anticipate when this event will occur in the future. format: YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='danceevent',
            name='title',
            field=models.CharField(help_text='User-facing name of the event. max 100 characters', max_length=100),
        ),
        migrations.AlterField(
            model_name='danceevent',
            name='website_url',
            field=models.URLField(help_text='Official website of this event. max: 300 characters', max_length=300),
        ),
    ]
